In [1]:
# principal component analysis


from numpy import array
from sklearn.decomposition import PCA

#define matrix
A=array([[1,2],[3,4],[5,6]])

print(A)

#create transform
pca=PCA(2)

#fit transform
pca.fit(A)

#access values and vectors
print(pca.components_)
print(pca.explained_variance_)

#transform data
B=pca.transform(A)

print(B)

C:\Users\sowndariya\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


[[1 2]
 [3 4]
 [5 6]]
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
[8.00000000e+00 2.25080839e-33]
[[-2.82842712e+00  2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 2.82842712e+00 -2.22044605e-16]]


C:\Users\sowndariya\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
