In [31]:

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
#math with constant tensors
const_a=tf.constant(3.6)
const_b=tf.constant(1.2)
total=const_a+const_b
quot=tf.div(const_a,const_b)

#math with random tensors
rand_a=tf.random_normal([3],2.0)
rand_b=tf.random_normal([3],1.0,4.0)
diff=tf.subtract(rand_a,rand_b)

#vector_multiplication
vec_a=tf.linspace(0.0,3.0,4)
vec_b=tf.fill([4,1],2.0)
prod=tf.multiply(vec_a,vec_b)
dot=tf.tensordot(vec_a,vec_b,1)

#matrix multiplication
mat_a=tf.constant([[2,3],[1,2],[4,5]])
mat_b=tf.constant([[6,4,1],[3,7,2]])
mat_prod=tf.matmul(mat_a,mat_b)

#execute the operations
with tf.Session() as sess:
    print('sum: %f' %sess.run(total))
    print('Quotient: %f' %sess.run(quot))
    print('Difference: ', sess.run(diff))
    print('Element-wise product: ', sess.run(prod))
    print('Dot Product: ',sess.run(dot))
    print('Matrix product: ',sess.run(mat_prod))

sum: 4.800000
Quotient: 3.000000
Difference:  [ 0.4288813 -2.358159  -1.431039 ]
Element-wise product:  [[0. 2. 4. 6.]
 [0. 2. 4. 6.]
 [0. 2. 4. 6.]
 [0. 2. 4. 6.]]
Dot Product:  [12.]
Matrix product:  [[21 29  8]
 [12 18  5]
 [39 51 14]]
